[package]
name = "rsfuzzy"
version = "0.1.1"
authors = ["Andrew Useckas <andrew@threatx.io>"]
description = "Basic Rust fuzzy logic library"
repository = "https://github.com/auseckas/rsfuzzy.git"
homepage = "https://github.com/auseckas/rsfuzzy.git"
license = "Apache-2.0"
